### ISSUE TITLE
why usart1 called in enroll_mainloop ?

### ISSUE THREAD

**Issue by IFurkanGungor** [brianrho/FPM-C#1]
Hı Brian Firstly,
I read your code so many times,when I started to create my libraries.I assume Usart1 used as Bluetooth module for serial monitor and Usart6 used for Fingerprint module.After these configurations applied I debug my code and started But code stay always in enroll_mainloop because of  this line: " while (uart_avail(&uart1) == 0); "  

``

  

>   void enroll_mainloop(void) 

    {
	  while (1) 
          {
		USART_Puts(USART1,"parmaginizi okutun lutfen\r\n");
		while (uart_avail(&uart1) == 0);

		USART_Puts(USART1,"parmaginizi kaydetmek icin bos sablon araniyor\r\n");
		int16_t fid;
		if (get_free_id(&fid))
			enroll_finger(fid);
		else
			USART_Puts(USART1,"No free slot in flash library!\r\n");
		while (uart_read_byte(&uart1) != -1);  // clear buffer
	   }
      }

//UART_MAX_RX_SIZE =256   uart1->rx_head=0,uart1->rx_tail=0 I received this values

uint16_t uart_avail(uart_t * port) 
{

    return ((uint16_t)(UART_MAX_RX_SIZE + port->rx_head - port->rx_tail)) % UART_MAX_RX_SIZE;
}

``

**Comment by brianrho** [comment]
- If you're going to use the provided `uart_drv.c/h` module, then you have to get rid of your own code, all that `USART_Puts()` stuff, especially when both are trying to use the same USART1. There's no need for any new USART code anyways, you can just call `printf()` as has been provided already (make sure to import `tiny_printf.c` into your project), which pipes stdout to USART1 by default.

- I don't know about any Bluetooth modules, I'd suggest you write a minimal example that uses only 2 USARTS: one (USART1) for debug purposes (where you can attach your Bluetooth module if you like), and the other (USART3) for the fingerprint sensor. This is what is used in the example already.

If you want to use USART6 or any other USART outside those two, you'll have to configure it yourself in `uart_drv.c`. It shouldn't be terribly difficult if you study how its done for USART1/3 in the file and just follow the pattern. You mostly have to configure the peripheral in `uart_init()` and then override the default USART interrupt handler `USARTx_IRQHandler()`, as you can see done for USART1/3.

- Regarding `while (uart_avail(&uart1) == 0);`, I suggest you check the original example and see where that was placed and what function it serves. `printf("Send any character to enroll a finger...\r\n");` vs `USART_Puts(USART1,"parmaginizi okutun lutfen\r\n");` which means a different thing, and should help you understand why the program would halt at that point, waiting for you.
