### ISSUE TITLE
stm32f10x_conf.h: No such file or directory

### ISSUE THREAD

**Issue by talhadq** [brianrho/FPM-C#2]
I am using stm32 nucleo f411RE with this code. after compilation it gives me the error that "stm32f10x_conf.h: No such file or directory". Is there any file that im missing to add ? Or is it about something else.

**Comment by brianrho** [comment]
Hello, yes, you're probably missing a file stm32f10x_conf.h, especially if you can't find it in your project. The example provided here was written for SPL. It wasn't written for HAL, which I suspect you're using?

Are you able to send and receive over UART with interrupts? If you can do that, integrating the example into your project won't be so difficult.

**Comment by talhadq** [comment]
I have done UART send and receive before on a different module (not fingerprint). In this example I think I just have to change the functions of uart_avail, uart_read and uart_write according to HAL. Your views ?

**Comment by talhadq** [comment]
Can you let me know about the HAL based library for the same module ? I am
searching for it for a quite longer time but could'nt find any help. Regards

**Comment by brianrho** [comment]
> In this example I think I just have to change the functions of uart_avail, uart_read and uart_write according to HAL

Yeah, almost. If you look in main.c, you see where the UART interface gets registered with the library:

```
	finger.avail_func = uart3_avail;
	finger.read_func = uart3_read;
	finger.write_func = uart3_write;
...
	if (fpm_begin(&finger, millis))
```
You just need to replace those uart3_avail/read/write with your own equivalents, written in HAL or whatever. Your UART must be interrupt-driven to even provide all these interfaces meaningfully, and also so you don't lose data easily. 

You also need to replace `millis` above with `HAL_GetTick`, which is simple enough.

After that, you should be able to just build and it should work. You can start with a very basic example (copied from main.c) that only calls `fpm_begin()` and get that to compile without errors first.

**Comment by brianrho** [comment]
> Can you let me know about the HAL based library for the same module

I don't know of any unfortunately -- but since STM32 HAL is a common platform these days, perhaps I can add an example project soon. That is, assuming the steps I gave above aren't enough to help you along.

**Comment by talhadq** [comment]
Thank you for the heads up. Let me just try doing that. Hopefully it will
be done soon.
Will wait for your HAL library example also.
Regards.

**Comment by brianrho** [comment]
Okay, I've added an STM32F4 HAL example. It was written for and tested on STM32F407VET6 but I think it should work for probably any STM32F4xx, being the whole point of a HAL. 

You _should_ be able to just clone/pull the repo as usual, import the project into your STM32CubeIDE workspace using `File -> Import -> Existing Projects into Workspace` and selecting the `stm32f4hal` folder in your clone. After successful import, simply `Build Project`.

The project makes use of symbolic links to link to the FPM library above it (in `FPM-C/src/*`) -- I don't know if the STM32CubeIDE-Import process will translate those links well onto your workspace, but if you get any build errors related to finding fpm.c/h, you may need to link to those files again. Let me know if you see any errors.

**Comment by brianrho** [comment]
Checking again, you'll probably also need to provide new linker scripts for your specific chip i.e. the .ld files like STM32F407VETX_FLASH.ld. Perhaps copy them from an existing F411 project and add them to this new project's Settings. See how far you get.

**Comment by talhadq** [comment]
Thank you so much for the help. Let me try this one and I'll let you know
if there are any issues.

**Comment by brianrho** [comment]
Sure. I'll close this in a bit, if there's no issues.

**Comment by talhadq** [comment]
I have started trying out this code, can you please let me know why you are
using 2 UARTS in the code ? Although we one for the Fingerprint module ?

**Comment by talhadq** [comment]
we need*

**Comment by brianrho** [comment]
USART1 is used for printf()-debugging whereas USART3 is for the fingerprint sensor. 
In main.c, you should see where `__io_putchar()` was defined to redirect printf() output to USART1.

**Comment by talhadq** [comment]
Great, It is working now with my STM32 F411RE. One last thing, is there any
function which we can use like fingerprint.scan() that will return us the
saved fingerprint number from the memory. Like if we enroll our finger at 2
then if we call the scan function it would return us 2 when we scan that
finger.

**Comment by brianrho** [comment]
Yeah, the library offers `fpm_search_database()` for that, among other functions -- check out the API in fpm.h.

I've added sample `fpm_search_database()` usage in the HAL example (main.c).

**Comment by talhadq** [comment]
Thank you. It worked. You helped me a lot in this library and I am really
grateful for that. God bless !

**Comment by brianrho** [comment]
Sure, good luck!
